### ISSUE TITLE
No visual hint when copying the C++ static analysis warnign message

### ISSUE THREAD

**Issue by NewtMa** [wwmyers/hackpot#2]
1. paste this code in a cpp file.
```
void cccc()
{
	int a = 9;
	switch (a)
	{
	case 0:
		std::string name = "conceo";
		break;

	default:
		break;
	}
}
```
2. enable C++ extension, there's going to be a warning regarding the `switch` clause, when hovering on it, the message shows, but there's no visual hint when copying that message.

**Comment by NewtMa** [comment]
I'm using the batman vs joker theme

**Comment by wwmyers** [comment]
This doesn't appear to be a theme issue. If you're asking for some kind of an alert message or visual effect that shows rather or not you've copied some text, that's not a theme issue, that's a software change request.
